spring:
  config:
    import: optional:file:.env[.properties]
  security:
    cors:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 10
      max-lifetime: 27000000
      idle-timeout: 60000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      config-url: /v3/api-docs/swagger-config

  logging:
    level:
      org:
        springframework:
          core:
            LocalVariableTableParameterNameDiscoverer: error
        hibernate:
          sql: debug
          type.descriptor.sql: trace
          sql.results.internal.ResultsHelper: INFO
      p6spy: debug

  decorator:
    datasource:
      p6spy:
        enable-logging: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_EXPIRATION}

firebase:
  credentials:
    path: src/main/resources/firebase/firebase-service-key.json